version: "3"

services:
  db:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: cache_redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  app:
    container_name: backend_app
    build: .
    image: app
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/stories
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./app:/app
volumes:
  postgres_data: {}
  redis_data: {}