spring:
  data:
    redis:
      host: cache_redis
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/stories
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER_EMAIL}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
server:
  servlet:
    session:
      cookie:
        same-site: strict
application:
  front-end-url: ${FRONT_END_URL}
  allowed-origins: ${FRONT_END_URL}
  login-success-url: ${FRONT_END_URL}/
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration: 900
    refresh-token:
      expiration: 604800
logging:
  level:
    liquibase: info
    org.springframework.security: info